apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: vs53orb8t-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:0c2f34c8571d0cce9b1d22ca8d526ac165522391@sha256:e21f2cc96b2c2dc2d6d46332496f6316fe82e4cbb5d376fafff4b1d92182c571
          name: container-image
